@startuml ../../images/association/state-container.png

skinparam shadowing false

!includesub ../components/state.puml!PROVIDER
!includesub ../components/container-app.puml!APP

Provider <..> App
note as N1
  <Provider store={store}>
      <App />
  </Provider>
end note
@enduml
